site_name: Structurizr MkDocs Sample
site_url: https://jbrestan.github.io/structurizr-mkdocs-pages/

plugins:
    - search
    - macros
    - mermaid2:
          arguments:
              securityLevel: 'loose'

theme:
    name: material
