site_name: Structurizr MkDocs Sample
site_url: https://example.com/

plugins:
    - search
    - macros
    - mermaid2:
          arguments:
              securityLevel: 'loose'

theme:
    name: material

